#!/usr/bin/awk -f


BEGIN { 
#SETTINGS
	
	RS = ORS = "\r\n"
	port = 8089
	host = "/inet/tcp/" port "/0/0"  # host string 

#END OF SETTINGS

	receive_handshake(header, host)
	#lets do it
	# 1) Calculate hash
	hash = calculate_hash(header["Sec-WebSocket-Key"]);
	# 2) ????
	# 3) send an answer
	answer_handshake(hash, host)
	printf(dataframe_encode(bytes, "hello")) |& host

	close(host)
} 

# you must know that client always send masked frames, server always send 
# unmasked frames
function dataframe_encode(bytes, payload){
# 		\x81\x05\x48\x65\x6c\x6c\x6f"
#		example
#
#     0                   1                   2                   3
#      0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
#     +-+-+-+-+-------+-+-------------+-------------------------------+
#     |F|R|R|R| opcode|M| Payload len |    Extended payload length    |
#     |I|S|S|S|  (4)  |A|     (7)     |             (16/64)           |
#     |N|V|V|V|       |S|             |   (if payload len==126/127)   |
#     | |1|2|3|       |K|             |                               |
#     +-+-+-+-+-------+-+-------------+ - - - - - - - - - - - - - - - +
#     |     Extended payload length continued, if payload len == 127  |
#     + - - - - - - - - - - - - - - - +-------------------------------+
#     |                               |Masking-key, if MASK set to 1  |
#     +-------------------------------+-------------------------------+
#     | Masking-key (continued)       |          Payload Data         |
#     +-------------------------------- - - - - - - - - - - - - - - - +
#     :                     Payload Data continued ...                :
#     + - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
#     |                     Payload Data continued ...                |
#     +---------------------------------------------------------------+

	payload_len = length(payload)
	split(payload, payload_chars, "")
	# final text frame 10000001
	bytes[0] = 0x81

	#payload length 
	if(payload_len > 125){
		bytes[1] = strtonum(sprintf("%2x", 126))
		bytes[2] = substr(payload_len, 0, 2)
		bytes[3] = substr(payload_len, 3)
	} else {
		bytes[1] = payload_len + 128
		bytes[2] = 0x00
		bytes[3] = 0x00
	}
	for(i = 0; i < 4; i++){
		frame = frame sprintf("%02x", bytes[i])
	}
	# then skip 4 bytes + 4 bytes + 2 bytes = 10 bytes
	for(i = 0; i < 10; i++){
		frame = frame sprintf("%02x", 0)
	}
	# and now encode payload
	printf payload_chars[0]
	for(i = 1; i < payload_len+1; i++){
		frame = frame sprintf("%02x", payload_chars[i])
	}	
	printf frame	
}

function answer_handshake(hash, host){
	#well, now i need
	# HTTP/1.1 101 Switching Protocols
	# Upgrade: websocket
	# Connection: Upgrade
	# Sec-WebSocket-Accept: HASH
	# Sec-WebSocket-Protocol: chat
	printf ("HTTP/1.1 101 Switching Protocols" ORS "Upgrade: websocket" ORS "Connection: Upgrade" ORS "Sec-WebSocket-Accept: %s" ORS ORS, hash) |& host
}

function receive_handshake(headers, host){
	while(host |& getline str){
		if (str == "")
			break
		match(str, "^([^:]*): (.*)$", tmp)
		headers[tmp[1]] = tmp[2]
	}
}

function calculate_hash(key){
	magic = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"
	cmd = sprintf("echo -n '%s' | openssl sha1 -binary | openssl base64", key magic)
	cmd | getline hash
	return substr(hash,0, 28)
}

function join(array, start, end, sep,    result, i)
{
    if (sep == SUBSEP) # magic value
       sep = ""
    result = array[start]
    for (i = start + 1; i <= end; i++)
        result = result sep array[i]
    return result
}
